/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package speedcliker_gharib_bousquet;

import java.util.Random;
import java.util.Scanner;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author elea
 */
public class Fenetredejeu extends javax.swing.JFrame {

    int Compteur = 0;
    Partie_speedclicker une_partie = new Partie_speedclicker();
    
    public Fenetredejeu() {
        initComponents();

        panneau_scorejoueur.setVisible(false);
        panneau_timer.setVisible(false);


        for (int i = 5; i >=0 ; i--) { // construit la grille en graphique en utlisant la grille de partie qui est composé d'une grille de bouton 
            for (int j = 0; j <= 5; j++) {
                BoutonGraphique boutonGraph = new BoutonGraphique(une_partie.GrilleDeJeu.grilleDeBoutons[i][j]); 
                panneau_grille.add(boutonGraph);
                
                boutonGraph.addActionListener((event) -> { // correspond aux différents évenement subi par le bouton comme par exemple lorsqu'il est cliqué
                    BoutonCliqué(boutonGraph); // on utilise la méthode bouton cliqué de partie sur nos boutons graphiques 
                });
                
            }

        }
    }
   
    public void BoutonCliqué(BoutonGraphique bouton_cliqué) {                   
            une_partie.ClicBouton(bouton_cliqué.BoutonAssociee);
            lbl_Compteur.setText(une_partie.J1.Nom + " : " + une_partie.J1.Score);
            if (une_partie.TempsRestant() == 1000){
                message.setText("ATTENTION plus que 10 secondes");
            }
            else if (une_partie.TempsRestant() == 0){
                message.setText("la partie est terminée");
            }
               
            panneau_grille.repaint(); 
 
 } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        panneau_grille = new javax.swing.JPanel();
        panneau_infosjoueur = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nom_joueur1 = new javax.swing.JTextField();
        btn_start = new javax.swing.JButton();
        panneau_scorejoueur = new javax.swing.JPanel();
        score_joueur = new javax.swing.JLabel();
        lbl_Compteur = new javax.swing.JLabel();
        panneau_timer = new javax.swing.JPanel();
        Tempsrestant = new javax.swing.JLabel();
        lbl_Timer = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();
        btl_ligne6 = new javax.swing.JButton();
        btl_ligne1 = new javax.swing.JButton();
        btl_ligne2 = new javax.swing.JButton();
        btl_ligne3 = new javax.swing.JButton();
        btl_ligne4 = new javax.swing.JButton();
        btl_ligne5 = new javax.swing.JButton();
        btn_col6 = new javax.swing.JButton();
        btn_col1 = new javax.swing.JButton();
        btn_col2 = new javax.swing.JButton();
        btn_col3 = new javax.swing.JButton();
        btn_col4 = new javax.swing.JButton();
        btn_col5 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneau_grille.setBackground(new java.awt.Color(255, 255, 255));
        panneau_grille.setLayout(new java.awt.GridLayout(6, 6));
        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 576, 576));

        panneau_infosjoueur.setBackground(new java.awt.Color(255, 204, 204));
        panneau_infosjoueur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Apple Braille", 0, 13)); // NOI18N
        jLabel1.setText("Pseudo du joueur :");
        panneau_infosjoueur.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        nom_joueur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_joueur1ActionPerformed(evt);
            }
        });
        panneau_infosjoueur.add(nom_joueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 90, 30));

        btn_start.setFont(new java.awt.Font("Apple Braille", 0, 13)); // NOI18N
        btn_start.setText("Jouer ");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        panneau_infosjoueur.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 80, 40));

        getContentPane().add(panneau_infosjoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 260, 120));

        panneau_scorejoueur.setBackground(new java.awt.Color(255, 204, 204));
        panneau_scorejoueur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        score_joueur.setFont(new java.awt.Font("Apple Braille", 0, 18)); // NOI18N
        score_joueur.setText("Score :");
        panneau_scorejoueur.add(score_joueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        lbl_Compteur.setFont(new java.awt.Font("Apple Braille", 0, 14)); // NOI18N
        lbl_Compteur.setText("Compteur");
        panneau_scorejoueur.add(lbl_Compteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 140, 60));

        getContentPane().add(panneau_scorejoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, 260, 120));

        panneau_timer.setBackground(new java.awt.Color(255, 204, 204));
        panneau_timer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tempsrestant.setFont(new java.awt.Font("Apple Braille", 0, 16)); // NOI18N
        Tempsrestant.setText("Temps restant : ");
        panneau_timer.add(Tempsrestant, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        lbl_Timer.setFont(new java.awt.Font("Apple Braille", 0, 14)); // NOI18N
        lbl_Timer.setText("Timer");
        panneau_timer.add(lbl_Timer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 70, 50));

        message.setColumns(20);
        message.setFont(new java.awt.Font("Apple Braille", 0, 12)); // NOI18N
        message.setRows(5);
        jScrollPane2.setViewportView(message);

        panneau_timer.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 240, 90));

        getContentPane().add(panneau_timer, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, 260, 170));

        btl_ligne6.setText("6");
        btl_ligne6.setToolTipText("");
        btl_ligne6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btl_ligne6ActionPerformed(evt);
            }
        });
        getContentPane().add(btl_ligne6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 70, 55));

        btl_ligne1.setText("1");
        btl_ligne1.setActionCommand("jButton1");
        btl_ligne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btl_ligne1ActionPerformed(evt);
            }
        });
        getContentPane().add(btl_ligne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 70, 55));

        btl_ligne2.setText("2");
        getContentPane().add(btl_ligne2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 166, 70, 55));

        btl_ligne3.setText("3");
        btl_ligne3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btl_ligne3ActionPerformed(evt);
            }
        });
        getContentPane().add(btl_ligne3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 262, 70, 55));

        btl_ligne4.setText("4");
        btl_ligne4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btl_ligne4ActionPerformed(evt);
            }
        });
        getContentPane().add(btl_ligne4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 358, 70, 55));

        btl_ligne5.setText("5");
        btl_ligne5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btl_ligne5ActionPerformed(evt);
            }
        });
        getContentPane().add(btl_ligne5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 454, 70, 55));

        btn_col6.setText("6");
        btn_col6.setToolTipText("");
        btn_col6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 70, 55));

        btn_col1.setText("1");
        btn_col1.setActionCommand("jButton1");
        btn_col1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 70, 55));

        btn_col2.setText("2");
        getContentPane().add(btn_col2, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 10, 70, 55));

        btn_col3.setText("3");
        btn_col3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col3, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 10, 70, 55));

        btn_col4.setText("4");
        btn_col4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col4, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 10, 70, 55));

        btn_col5.setText("5");
        btn_col5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col5, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 10, 70, 55));

        setBounds(0, 0, 1036, 673);
    }// </editor-fold>//GEN-END:initComponents

    private void nom_joueur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_joueur1ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_nom_joueur1ActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        // TODO add your handling code here:
        
        panneau_scorejoueur.setVisible(true);
        panneau_timer.setVisible(true);
        debuter_partie(); 
        btn_start.setEnabled(false);
        panneau_grille.repaint();
    }//GEN-LAST:event_btn_startActionPerformed

    private void btl_ligne6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btl_ligne6ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btl_ligne6ActionPerformed

    private void btl_ligne3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btl_ligne3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btl_ligne3ActionPerformed

    private void btl_ligne4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btl_ligne4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btl_ligne4ActionPerformed

    private void btl_ligne5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btl_ligne5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btl_ligne5ActionPerformed

    private void btl_ligne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btl_ligne1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btl_ligne1ActionPerformed

    private void btn_col6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_col6ActionPerformed

    private void btn_col1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_col1ActionPerformed

    private void btn_col3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_col3ActionPerformed

    private void btn_col4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_col4ActionPerformed

    private void btn_col5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_col5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetredejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetredejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetredejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetredejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetredejeu().setVisible(true);
            }
        });
    }

    public void debuter_partie() {
       
        String nomJoueur1 = nom_joueur1.getText();// recuperer le nom du joueur    
        une_partie.debut_partie(nomJoueur1);
        
        lbl_Compteur.setText(une_partie.J1.Nom + " : " + une_partie.J1.Score);// mise à jour du compteur
        message.setText("c'est partie !!!");

        
        mise_à_jour_chrono();// mise en place du timer 

    }
    

    public void mise_à_jour_chrono() {
        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            public void run() {
                lbl_Timer.setText("" + une_partie.TempsRestant()/1000 + "s"); //met à jour le chrono à chaque 0,5 seconde
            }
            
        }, 0, 500);
    }


       


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tempsrestant;
    private javax.swing.JButton btl_ligne1;
    private javax.swing.JButton btl_ligne2;
    private javax.swing.JButton btl_ligne3;
    private javax.swing.JButton btl_ligne4;
    private javax.swing.JButton btl_ligne5;
    private javax.swing.JButton btl_ligne6;
    private javax.swing.JButton btn_col1;
    private javax.swing.JButton btn_col2;
    private javax.swing.JButton btn_col3;
    private javax.swing.JButton btn_col4;
    private javax.swing.JButton btn_col5;
    private javax.swing.JButton btn_col6;
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_Compteur;
    private javax.swing.JLabel lbl_Timer;
    private javax.swing.JTextArea message;
    private javax.swing.JTextField nom_joueur1;
    private javax.swing.JPanel panneau_grille;
    private javax.swing.JPanel panneau_infosjoueur;
    private javax.swing.JPanel panneau_scorejoueur;
    private javax.swing.JPanel panneau_timer;
    private javax.swing.JLabel score_joueur;
    // End of variables declaration//GEN-END:variables
}
